# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 

  workflow_dispatch:

   inputs:

     auth:

        description: 'Past rom link'

        required: true

        default: ''

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i

      # Runs a single command using the runners shell
      - name: Setup Tools and Environment
        run: git clone https://github.com/erfanoabdi/ErfanGSIs && cd ErfanGSIs && sed -i '143i\    *"13"*) flag=true' make.sh && cp -r roms/12 roms/13 && cp -r prebuilt/12 prebuilt/13 && cp -r prebuilt/vendor_vndk/make12.sh prebuilt/vendor_vndk/make13.sh 




      # Runs a set of commands using the runners shell
      - name: Build GSI
        run: |
          cd Erfan* && bash url2GSI.sh ${{ github.event.inputs.auth }} Generic -b
